name: IT Bench Agent Registration
description: Register your IT Bench Agent for benchmarking
title: "[Registration]: < agent name here >"
labels: ["registration", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in benchmarking an IT Bench Agent. 
        Please fill out this form to request connection details for the IT Bench service.
  - type: input
    id: agent-owner-email
    attributes:
      label: Contact
      description: Who should be the main point of contact for this agent?
      placeholder: you@somewhere.com
    validations:
      required: true
  - type: input
    id: agent-name
    attributes:
      label: Agent Name
      placeholder: my-itbench-agent
    validations:
      required: true
  - type: dropdown
    id: agent-type
    attributes:
      label: Agent Type
      description: What type of agent is this?
      options:
        - SRE
        - CISO
        - FinOps
      default: 0
    validations:
      required: true
  - type: dropdown
    id: agent-level
    attributes:
      label: Agent Level
      description: What level of agent is this?
      options:
        - Beginner
        - Intermediate
        - Expert
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: scenario-categories
    attributes:
      label: Agent Scenarios
      description: You may select more than one, options not applicable to the agent type will be ignored.
      options:
        - label: (SRE) resource unavailability
        - label: (CISO) Kubernetes in Kyverno
        - label: (CISO) Kubernetes in OPA
        - label: (CISO) Kubernetes in Kyverno Update
        - label: (CISO) RHEL9 in OPA
        - label: (FinOps) Something
  - type: input
    id: repo_url
    attributes:
      label: "Config Repo"
      description: |
        Provide the GitHub Repository URL that we will create data required for benchmark.
        Please install the `it-bench-gitops-1` GitHub App in the repository described in **Instruction of `it-bench-gitops-1` GitHub App install**.
      placeholder: "e.g. https://github.ibm.com/your_org/repo_name"
    validations:
      required: true
  - type: markdown
    
    attributes:
      value: |
        Once this onboarding request has been approved, we will need a github repository to send your agent connection details to.

        Please follow the following steps:

        1. Create an empty repository, make sure that it is set to private.
        2. Install this GitHub App into your repository that you just created.

      
  - type: markdown
    attributes:
      value: Thank you for completing this form, we will review your request shortly.