name: Leaderboard Update
on:
  repository_dispatch:
    types: [update_leaderboard]
  issues:
    types: [labeled]

jobs:
  update_leaderboard:
    runs-on: ubuntu-latest
    name: Update the Leaderboard
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Pull Leaderboard data
        id: get-leaderboard-data
        run: |
          echo "Requesting Leaderboard data from API"
          # We would make a CURL request to the API to get the csv data here
          # For now, we'll just mock it
        

            if curl -o leaderboard.csv https://people.sc.fsu.edu/~jburkardt/data/csv/deniro.csv; then
              echo "CSV download successful."
            else
              echo "CSV download failed."
              exit 1
            fi

      - name: Read CSV
        id: csv
        uses: juliangruber/read-file-action@v1
        with:
          path: ./leaderboard.csv

         
      - name: convert-csv-to-markdown
        id: csv-to-markdown
        uses: petems/csv-to-md-table-action@master
        with:
          csvinput: ${{ steps.csv.outputs.content }}
      - name: generate-readme
        id: generate-readme
        env:
          CONTENT: |
            # IT Bench Leaderboard\n\n

            ${{steps.csv-to-markdown.outputs.markdown-table}}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          echo $CONTENT > README.md

          git checkout main

          git add README.md

          git commit -m "Update leaderboard"

          git push origin main


          



      
      
